package fr.hopelessworld.plugin.strategy.impl;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collection;

import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import fr.hopelessworld.plugin.analyzer.AnalizedEntity;
import fr.hopelessworld.plugin.strategy.GeneratorStrategy;

public class AngularSpringDataRestCustomControllerStrategyTest {

	private GeneratorStrategy strategy = new AngularSpringDataRestCustomControllerStrategy();

	@Rule
	public TemporaryFolder folder = new TemporaryFolder();

	@Test
	public void testGenerate() throws Exception {

		// cerate the fakeEntity
		Collection<AnalizedEntity> entities = new ArrayList<>();
		AnalizedEntity playerEntity = mock(AnalizedEntity.class);
		entities.add(playerEntity);

		when(playerEntity.getSimpleName()).thenReturn("Player");
		when(playerEntity.getPackageName()).thenReturn("fr.hopeless.test.entity");

		AnalizedEntity teamEntity = mock(AnalizedEntity.class);
		entities.add(teamEntity);

		when(teamEntity.getSimpleName()).thenReturn("Team");
		when(teamEntity.getPackageName()).thenReturn("fr.hopeless.test.entity");

		File tempDirectory = folder.newFolder();

		strategy.generate(tempDirectory, entities);

		Path pathPackage = Paths.get(tempDirectory.getAbsolutePath(), "fr/hopelessworld/autogenerated");
		Assert.assertTrue("directory not created", Files.exists(pathPackage));

		Path pathEntitySpecification = Paths.get(tempDirectory.getAbsolutePath(),
				"fr/hopelessworld/autogenerated/specification/EntitySpecification.java");
		Assert.assertTrue("Specification file not created", Files.exists(pathEntitySpecification));

		Path pathSpecificationBuilder = Paths.get(tempDirectory.getAbsolutePath(),
				"fr/hopelessworld/autogenerated/builder/EntitySpecificationsBuilder.java");
		Assert.assertTrue("EntitySpecificationsBuilder file not created", Files.exists(pathSpecificationBuilder));

		Path pathSearchCriteria = Paths.get(tempDirectory.getAbsolutePath(),
				"fr/hopelessworld/autogenerated/specification/SearchCriteria.java");
		Assert.assertTrue("SearchCriteria file not created", Files.exists(pathSearchCriteria));

		Path pathPlayerRestController = Paths.get(tempDirectory.getAbsolutePath(),
				"fr/hopelessworld/autogenerated/controller/PlayerRestController.java");
		Assert.assertTrue("RestController file not created", Files.exists(pathPlayerRestController));

		Path pathTeamRestController = Paths.get(tempDirectory.getAbsolutePath(),
				"fr/hopelessworld/autogenerated/controller/TeamRestController.java");
		Assert.assertTrue("RestController file not created", Files.exists(pathTeamRestController));

	}

}
